[package]
name = "filesearcherV5-web"
version = "0.2.0"
edition = "2024"

[lib]
name = "filesearcherv5_web"
path = "src/lib.rs"

[[bin]]
name = "filesearcherV5-web"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
axum = "0.8"
futures-util = "0.3"
helper_lib = { git = "https://github.com/rayzinnz/rust-helper-lib.git", features = ["log", "crypto", "datetime", "paths"] }
log = "0.x"
simplelog = "0.x"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
toml = "0.8"
zstd = "0.14.0"
base64 = "0.23.1"

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
tempfile = "3"
